language: python
python:
    - "3.6"

install:
    - pip install pytest pytest-cov pytest-codestyle
    - pip install -e .

script:
    - pytest --codestyle
             --cov karst
             -v --cov-report term-missing tests

