language: python
python:
    - "3.6"

install:
    - pip install --upgrade pytest
    - pip install pytest-cov pytest-codestyle
    - pip install -e .

script:
    - pytest --codestyle
             --cov karst
             -v --cov-report term-missing tests

notifications:
  email:
    on_success: never
