language: python
python:
    - "3.6"

install:
    - pip install --upgrade pytest
    - pip install pytest-cov pytest-codestyle codecov
    - pip install -e .

script:
    - pytest --codestyle karst
             --cov karst
             --cov-report=xml
             -v --cov-report term-missing tests

after_success:
  - codecov

notifications:
  email:
    on_success: never
